(package "eglot-ltex"
         "0.1.0"
         "Eglot Clients for LTEX")

(website-url "https://github.com/emacs-languagetool/eglot-ltex")
(keywords "eglot" "languagetool" "checker")

(package-file "eglot-ltex.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")
(depends-on "eglot")
(depends-on "f")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
